package com.excelr.project.travel.planner.entity;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
@Table(name = "flight_bookings")
public class FlightBooking {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "booking_flight_seq_gen")
    @SequenceGenerator(name = "booking_flight_seq_gen", sequenceName = "FLIGHT_SEQ", allocationSize = 1)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID", nullable = false)
    private UserAccount userAccount;

    @Column(name = "ORIGIN")
    private String origin;

    @Column(name = "DESTINATION")
    private String destination;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "DEPARTURE_DATE")
    private LocalDateTime departureDate;

    @Column(name = "PASSENGERS")
    private int passengers;

    @Column(name = "FLIGHT_NUMBER")
    private String flightNumber;

    @Column(name = "AIRLINE")
    private String airline;

    @Column(name = "BOOKING_STATUS")
    private String bookingStatus;

    @Column(name = "BOOKED_AT")
    private LocalDateTime bookedAt;

    @Column(name="PRICE")
    private Double price;

    // Getters and setters generated by Lombok @Data
}
